# ELU机械臂运动控制框架配置文件

robot_arms:
  elu_arm_1:
    plugin_type: "elu_adapter/EluAdapter"
    ip_address: "192.168.1.100"
    port: 8080
    dof: 6
    max_payload: 5.0  # kg
    max_reach: 1.2    # meters
    joint_limits:     # [min, max] for each joint (radians)
      - [-3.14159, 3.14159]  # Joint 1
      - [-3.14159, 3.14159]  # Joint 2
      - [-3.14159, 3.14159]  # Joint 3
      - [-3.14159, 3.14159]  # Joint 4
      - [-3.14159, 3.14159]  # Joint 5
      - [-3.14159, 3.14159]  # Joint 6
    workspace_limits:
      x_min: -1.2
      x_max: 1.2
      y_min: -1.2
      y_max: 1.2
      z_min: 0.0
      z_max: 2.0

  elu_arm_2:
    plugin_type: "elu_adapter/EluAdapter"
    ip_address: "192.168.1.101"
    port: 8080
    dof: 6
    max_payload: 5.0
    max_reach: 1.2
    joint_limits:
      - [-3.14159, 3.14159]
      - [-3.14159, 3.14159]
      - [-3.14159, 3.14159]
      - [-3.14159, 3.14159]
      - [-3.14159, 3.14159]
      - [-3.14159, 3.14159]
    workspace_limits:
      x_min: -1.2
      x_max: 1.2
      y_min: -1.2
      y_max: 1.2
      z_min: 0.0
      z_max: 2.0

# 默认设置
default_settings:
  default_speed_ratio: 0.5
  default_acceleration_ratio: 0.5
  control_frequency: 100  # Hz
  status_publish_frequency: 10  # Hz
